/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import FormPredavac.*;
import FormPredavac.*;
import controller.ClientController;
import domain.Grupa;
import domain.Kurs;
import domain.Polaznik;
import domain.Predavac;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelListaPolaznika;

/**
 *
 * @author Neon
 */
public class FormIzmenaGrupe extends javax.swing.JDialog {

    /**
     * Creates new form FormIzmenaGrupe
     */
    private Grupa g;
    
    public FormIzmenaGrupe(JFrame parent, boolean modal, Grupa g) {
        super(parent, modal);
        initComponents();
        this.g = g;
        setLocationRelativeTo(null);
        vratiKurseve();
        vratiPredavace();
        lblGrupa.setText("GrupaID: " + String.valueOf(g.getGrupaID()));
        txtNazivGrupe.setText(g.getNazivGrupe());
        txtMaxBrojPolaznika.setText(String.valueOf(g.getMaxBrojPolaznika()));
        cbKurs.setSelectedItem(g.getKurs());
        cbPredavac.setSelectedItem(g.getPredavac());
        TableModelListaPolaznika model = new TableModelListaPolaznika(this.g);
        Thread th = new Thread(model);
        th.start();
        tblListaPolaznikaGrupe.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnOtkazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNazivGrupe = new javax.swing.JTextField();
        txtMaxBrojPolaznika = new javax.swing.JTextField();
        btnObrisi = new javax.swing.JButton();
        lblGrupa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbPredavac = new javax.swing.JComboBox();
        cbKurs = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListaPolaznikaGrupe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnObrisiPolaznikaIzGrupe = new javax.swing.JButton();
        btnDodajPolaznika = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Sacuvaj promene");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel4.setText("Naziv grupe:");

        jLabel5.setText("Maksimalni broj polaznika:");

        btnObrisi.setText("Obrisi celu grupu");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblGrupa.setText("GrupaID");

        jLabel8.setText("Predavac:");

        jLabel1.setText("Kurs:");

        cbPredavac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbKurs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblListaPolaznikaGrupe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblListaPolaznikaGrupe);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Pregled polaznika grupe:");

        btnObrisiPolaznikaIzGrupe.setText("Obrisi polaznika");
        btnObrisiPolaznikaIzGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPolaznikaIzGrupeActionPerformed(evt);
            }
        });

        btnDodajPolaznika.setText("Dodaj polaznika");
        btnDodajPolaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPolaznikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGrupa)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNazivGrupe)
                                    .addComponent(txtMaxBrojPolaznika)
                                    .addComponent(cbPredavac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbKurs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnObrisiPolaznikaIzGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnDodajPolaznika, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrupa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNazivGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxBrojPolaznika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPredavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiPolaznikaIzGrupe)
                    .addComponent(btnDodajPolaznika))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (txtNazivGrupe.getText().isEmpty() || txtMaxBrojPolaznika.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }

        String nazivGrupe = txtNazivGrupe.getText();
        try {
            int maxBrojPolaznika = Integer.parseInt(txtMaxBrojPolaznika.getText());
            Kurs k = (Kurs) cbKurs.getSelectedItem();
            Predavac p = (Predavac) cbPredavac.getSelectedItem();

            Grupa grupa = new Grupa(g.getGrupaID(), nazivGrupe, maxBrojPolaznika, k, p);

            ArrayList<Grupa> listaGrupa = ClientController.getInstance().getAllGrupa();
            for (Grupa g1 : listaGrupa) {
                if (grupa.equals(g1)) {
                    if (grupa.getGrupaID() != g1.getGrupaID()) {
                        JOptionPane.showMessageDialog(this, "Grupa vec postoji!");
                        return;
                    }
                }
            }

            if(maxBrojPolaznika < vratiBrojPolaznika()){
                JOptionPane.showMessageDialog(this, "Ne mozete staviti manji kapacitet grupe od onoga koji je trenutno!");
                return;
            }
            
            ClientController.getInstance().editGrupa(grupa);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "U polje za maksimalni broj polaznika morate uneti ceo broj!");
            return;
        } catch (Exception ex) {
            System.out.println("OVDE BACA STREAM CORRUPTED EXC");
            Logger.getLogger(FormIzmenaGrupe.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Uspesno izmenjena grupa.");
        this.dispose();

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "obrisete grupu? Kada je obrisete, zajedno s njom ce se obrisati svi njeni polaznici.", "Potvrda", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {

//                ArrayList<Polaznik> listaPolaznika = ClientController.getInstance().getAllPolaznik();
//                for (Polaznik p : listaPolaznika) {
//                    if (p.getGrupa().getGrupaID() == g.getGrupaID()) {
//                        JOptionPane.showMessageDialog(this, "Ne mozete obrisati grupu u kojoj ima aktivnih polaznika!");
//                        return;
//                    }
//                }

                TableModelListaPolaznika model = (TableModelListaPolaznika) tblListaPolaznikaGrupe.getModel();
                ArrayList<Polaznik> listaPolaznika = (ArrayList<Polaznik>) model.getLista();
                
                for (Polaznik polaznik : listaPolaznika) {
                    ClientController.getInstance().deletePolaznik(polaznik);
                }
                
                ClientController.getInstance().deleteGrupa(g);
//                JOptionPane.showMessageDialog(this, "Uspesno obrisan predavac!");
//                this.dispose();

            } catch (Exception ex) {
                //Logger.getLogger(FormIzmenaPredavaca.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Uspesno obrisana grupa!");
            this.dispose();
        }


    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnObrisiPolaznikaIzGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPolaznikaIzGrupeActionPerformed
        try {
            TableModelListaPolaznika model = (TableModelListaPolaznika) tblListaPolaznikaGrupe.getModel();
            int row = tblListaPolaznikaGrupe.getSelectedRow();
            if (row < 0) {
                return;
            }

            model.obrisiPolaznika(row, this);
            
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnObrisiPolaznikaIzGrupeActionPerformed

    private void btnDodajPolaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPolaznikaActionPerformed
        if((vratiBrojPolaznika()+1) > g.getMaxBrojPolaznika()){
            JOptionPane.showMessageDialog(this, "Grupa je popunjena! Ne mozete dodavati nove polaznike.");
           return;
        }
        new FormDodajPolaznika((Frame) this.getParent(), rootPaneCheckingEnabled, this.g).setVisible(true);
       
//        TableModelListaPolaznika model = (TableModelListaPolaznika) tblListaPolaznikaGrupe.getModel();
//        lblBrojPolaznikaUGrupi.setText("Broj polaznika u grupi: " + vratiBrojPolaznika());
    }//GEN-LAST:event_btnDodajPolaznikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIzmenaGrupe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIzmenaGrupe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIzmenaGrupe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIzmenaGrupe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajPolaznika;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiPolaznikaIzGrupe;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cbKurs;
    private javax.swing.JComboBox cbPredavac;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblGrupa;
    private javax.swing.JTable tblListaPolaznikaGrupe;
    private javax.swing.JTextField txtMaxBrojPolaznika;
    private javax.swing.JTextField txtNazivGrupe;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void vratiKurseve() {
        ArrayList<Kurs> listaKurseva = new ArrayList<>();

        try {
            listaKurseva = ClientController.getInstance().getAllKurs();
            cbKurs.removeAllItems();
            for (Kurs kurs : listaKurseva) {
                cbKurs.addItem(kurs);

            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void vratiPredavace() {
        ArrayList<Predavac> listaPredavaca = new ArrayList<>();

        try {
            listaPredavaca = ClientController.getInstance().getAllPredavac();
            cbPredavac.removeAllItems();
            for (Predavac predavac : listaPredavaca) {
                cbPredavac.addItem(predavac);

            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int vratiBrojPolaznika(){
        TableModelListaPolaznika model = (TableModelListaPolaznika) tblListaPolaznikaGrupe.getModel();
        return model.getRowCount();
    }
    
   

}
